POST http://0.0.0.0:3000/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "tobyB",
    "password": "secretPassword"
}

###

POST http://0.0.0.0:3000/chatSupport

###

GET http://0.0.0.0:3000/hotels HTTP/1.1

###

GET http://0.0.0.0:3000/hotel/626bc51b7153b347910168fa HTTP/1.1

###

GET http://0.0.0.0:3000/hotels/Nep HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IkJvc3RvZW4gVG9ieSIsImNpdHkiOiJLb3J0cmlqayIsIm5iZiI6MTY1MTMzNjQzMCwiZXhwIjoxNjU0OTM2NDMwLCJpc3MiOiJodHRwczovLzAuMC4wLjA6MzAwMCIsImF1ZCI6ImhvdGVsX2FwaV91c2VycyJ9.C_YFxF5a2gMZ1maksDvsvoevLNq846dEROlwyC5f59g

###

GET http://0.0.0.0:3000/hotels/Filter/StarRating=1.5&PricePerNightMin=90&PricePerNightMax=2000

###

GET http://0.0.0.0:3000/hotels/Region/Brugge

###

GET http://0.0.0.0:3000/hotels/Region/West-Vlaanderen

###
GET http://0.0.0.0:3000/hotels/Filter/Namepiece/PricePerNightMin=90&PricePerNightMax=250&StarRating=1&Namepiece=Nep

###

GET http://0.0.0.0:3000/hotels/Region/Filter/Namepiece/Region=Brugge&PricePerNightMin=90&PricePerNightMax=400&StarRating=2&Namepiece=Ter 

###

GET http://0.0.0.0:3000/hotels/Region/Filter/Namepiece/Region=Nieuwpoort&PricePerNightMin=90&PricePerNightMax=400&StarRating=2&Namepiece=Nep 

###


GET http://0.0.0.0:3000/hotels/Region/Filter/Region=Brugge&PricePerNightMin=10&PricePerNightMax=2000&StarRating=2

###

GET http://0.0.0.0:3000/hotel/roomtype/Id=626d64ba27203ca0b8d258e2&NumberOfBeds=1&SquareMeters=20&PriceMax=500&PriceMin=50&Television=false&Breakfast=false&Airco=false&Wifi=false&View=false

###

POST http://localhost:3000/hotel HTTP/1.1
Content-Type: application/json

{
    "Name": "Neptunus",
    "City": "Nieuwpoort",
    "Address": "Brugsevaart 48",
    "Province": "West-Vlaanderen",
    "Description": "NEPTUNUS ligt in Nieuwpoort, op 2,7 km van het strand van Westende, en biedt accommodatie met een restaurant, gratis privéparkeergelegenheid, een fitnesscentrum en een bar. Prachtige kamers , stuk voor stuk pareltjes. Mooi ingericht en voorzien van alle gemak. Vriendelijke ontvangst en begeleiding. Op en top gastheer/vrouw. Super ruim ontbijt en zeer lekker. Ook een aanrader om te blijven eten in de brasserie. Prachtig uitzicht over de jachthaven en de omringende velden. Op en top aanrader.",
    "StarRating": 2,
    "Longitude": 2.7721063,
    "Latitude": 51.1382443,
    "PricePerNightMin": 99,
    "PricePerNightMax": 210,
    "image": "https://cf.bstatic.com/xdata/images/hotel/square600/335587995.webp?k=e52822ba4a04d4b4bf57c425cfca110c4e162fdcf4351efbd3b9f07c3b234a5e&o=&s=1",
    "Reviews":[{
        "Id": "626bc4be7153b347910168f4",
        "Author": "Vandeweyer",
        "StarRating": 4,
        "HotelName": "Neptunus",
        "Image": "https://graph.facebook.com/v2.9/802992566485650/picture?type=square&height=64&width=64",
        "ReviewDescription": "They were very kind and helpfull. The breakfast was amazing and I'll go back for sure!"
    },
    {
        "Id": "626bc4d17153b347910168f5",
        "Author": "Caitly",
        "StarRating": 3.5,
        "HotelName": "Neptunus",
        "Image": "https://cf.bstatic.com/static/img/review/avatars/ava-c/315f92289c481a16de5ee7737aa1b5fd531afcce.png",
        "ReviewDescription": "The enviroment is very beautifull and I'll come back next year."
    },
    {
        "Id": "626bc4de7153b347910168f6",
        "Author": "Wilfried",
        "StarRating": 4.5,
        "HotelName": "Neptunus",
        "Image": "https://cf.bstatic.com/static/img/review/avatars/ava-w/743312ca303f4a4be7af10e6d1015d40a0ce81a4.png",
        "ReviewDescription": "The rooms were delightfull and the decoration was sublime."
    }],
    "RoomTypes":[{
        "Id": "626bc3e17153b347910168ee",
        "Name": "Presidential",
        "NumberOfBeds": "2",
        "SquareMeters": 50,
        "Television": true,
        "Breakfast": true,
        "Airco": true,
        "Wifi": true,
        "View": true,
        "Price": 210,
        "HotelName": "Neptunus",
        "Image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/350348570.jpg?k=b09a56f8c5af3a67ada5f08fb7ef7a4b22a0b8cb8d01b32ba0cb77b00bf5e256&o="
    },
    {
        "Id": "626bc3f47153b347910168ef",
        "Name": "Standard",
        "NumberOfBeds": 2,
        "SquareMeters": 30,
        "Television": true,
        "Breakfast": false,
        "Airco": true,
        "Wifi": false,
        "View": false,
        "Price": 120.56,
        "HotelName": "Neptunus",
        "Image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/350348540.jpg?k=d14a5db9989573ba354a60657bc3a4b0a14a04576f5fed58cab1dfe7e26b152b&o="
    },
    {
        "Id": "626bc41e7153b347910168f0",
        "Name": "Economic",
        "NumberOfBeds": 1,
        "SquareMeters": 20,
        "Television": false,
        "Breakfast": false,
        "Airco": false,
        "Wifi": false,
        "View": false,
        "Price": 99,
        "HotelName": "Neptunus",
        "Image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/350348631.jpg?k=2c3236726e2f72dd1aa2b25395bd3c4f650c7f467c1ecb8e80852f867f32862e&o="
    }]
}

###

POST http://localhost:3000/hotel HTTP/1.1
Content-Type: application/json

{
    "Name": "Ter Brughe",
    "City": "Brugge",
    "Address": "Oost-Gistelhof 2",
    "Province": "West-Vlaanderen",
    "Description": "Dit schilderachtige hotel bevindt zich in een 15e-eeuws gebouw aan een gracht. Het ligt op 5 minuten lopen van het chocolademuseum Choco-Story en op 8 minuten lopen van de Markt. De sfeervol ingerichte kamers hebben gratis wifi, een flatscreen-tv, een kluisje en een minikoelkast. Sommige kijken uit op de gracht. Enkele luxere kamers hebben een balkenplafond of een gewelfd plafond. Roomservice is 24 uur per dag beschikbaar. In een gewelfde kelder bevindt zich een gezellige eetkamer. Het hotel heeft ook een bar, een terras en een lounge. Er is een ontbijtbuffet (tegen een toeslag).",
    "StarRating": 4,
    "Longitude": 3.2254868,
    "Latitude": 51.2138264,
    "PricePerNightMin": 215,
    "PricePerNightMax": 273,
    "Image": "https://cf.bstatic.com/xdata/images/hotel/square600/311191353.webp?k=8ccdc44d94ec0a75ef4eca774617c4aab068e30005b35bf52cc61dd43094f32e&o=&s=1",
    "Reviews":[{
        "Id": "626bc4ed7153b347910168f7",
        "Author": "Stewart",
        "StarRating": 4.5,
        "HotelName": "Ter Brughe",
        "Image": "https://cf.bstatic.com/static/img/review/avatars/ava-s/d321d61d78a8fa310843e1967dca38e6276b92aa.png",
        "ReviewDescription": "They where friendly and the breakfast was nice. Good location."
    },
    {
        "Id": "626bc4fb7153b347910168f8",
        "Author": "Jorn",
        "StarRating": 5,
        "HotelName": "Ter Brughe",
        "Image": "https://graph.facebook.com/v2.9/2497254647071309/picture?type=square&height=64&width=64",
        "ReviewDescription": "The location is central in the city. You're in no time in the center of Bruges."
    },
    {
        "Id": "626bc50a7153b347910168f9",
        "Author": "Sara",
        "StarRating": 3.5,
        "HotelName": "Ter Brughe",
        "Image": "https://lh3.googleusercontent.com/a-/AOh14Gi0QpcHD6XKePTvetRgGFTJB1w7AV_C3zrUH9p5rw=s96-c",
        "ReviewDescription": "There was an authentic vibe in the hotel, but there wasn't a shower."
    }],
    "RoomTypes":[{
        "Id": "626bc4397153b347910168f1",
        "Name": "King room",
        "NumberOfBeds": 3,
        "SquareMeters": 40,
        "Television": true,
        "Breakfast": true,
        "Airco": true,
        "Wifi": true,
        "View": true,
        "Price": 273,
        "HotelName": "Ter Brughe",
        "Image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/311191609.jpg?k=1c95c6a7a93f12e232871fa7379970fa3089e9ce8527daa50cf75337d896e465&o="
    },
    {
        "Id": "626bc48c7153b347910168f2",
        "Name": "Deluxe room",
        "NumberOfBeds": 2,
        "SquareMeters": 30,
        "Television": true,
        "Breakfast": true,
        "Airco": true,
        "Wifi": true,
        "View": false,
        "Price": 240,
        "HotelName": "Ter Brughe",
        "Image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/311191598.jpg?k=21cc7ae84af70ed7bdff087ca8b94a914df8de7365c5adbe5b6170a00795c123&o="
    },
    {
        "Id": "626bc49e7153b347910168f3",
        "Name": "Economic",
        "NumberOfBeds": 2,
        "SquareMeters": 20,
        "Television": true,
        "Breakfast": true,
        "Airco": false,
        "Wifi": true,
        "View": false,
        "Price": 215,
        "HotelName": "Ter Brughe",
        "Image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/321943472.jpg?k=6876471af7e3e8e5b0fc44c4ed94ee161c394ff25058655cb1742f2cb0bd2dd3&o="
    }]
}

###

PUT http://0.0.0.0:3000/hotel HTTP/1.1
Content-Type: application/json

{
    "Id": "626bc5207153b347910168fb",
    "Name": "Ter Brughe",
    "City": "Brugge",
    "Address": "Oost-Gistelhof 2",
    "Province": "West-Vlaanderen",
    "Description": "Dit schilderachtige hotel bevindt zich in een 15e-eeuws gebouw aan een gracht. Het ligt op 5 minuten lopen van het chocolademuseum Choco-Story en op 8 minuten lopen van de Markt. De sfeervol ingerichte kamers hebben gratis wifi, een flatscreen-tv, een kluisje en een minikoelkast. Sommige kijken uit op de gracht. Enkele luxere kamers hebben een balkenplafond of een gewelfd plafond. Roomservice is 24 uur per dag beschikbaar. In een gewelfde kelder bevindt zich een gezellige eetkamer. Het hotel heeft ook een bar, een terras en een lounge. Er is een ontbijtbuffet (tegen een toeslag).",
    "StarRating": 4,
    "Longitude": 3.2254868,
    "Latitude": 51.2138264,
    "PricePerNightMin": 215,
    "PricePerNightMax": 273,
    "Image": "https://cf.bstatic.com/xdata/images/hotel/square600/311191353.webp?k=8ccdc44d94ec0a75ef4eca774617c4aab068e30005b35bf52cc61dd43094f32e&o=&s=1",
    "Reviews":[{
        "Id": "626bc4ed7153b347910168f7",
        "Author": "Stewart",
        "StarRating": 4.5,
        "HotelName": "Ter Brughe",
        "Image": "https://cf.bstatic.com/static/img/review/avatars/ava-s/d321d61d78a8fa310843e1967dca38e6276b92aa.png",
        "ReviewDescription": "They where friendly and the breakfast was nice. Good location."
    },
    {
        "Id": "626bc4fb7153b347910168f8",
        "Author": "Jorn",
        "StarRating": 5,
        "HotelName": "Ter Brughe",
        "Image": "https://graph.facebook.com/v2.9/2497254647071309/picture?type=square&height=64&width=64",
        "ReviewDescription": "The location is central in the city. You're in no time in the center of Bruges."
    },
    {
        "Id": "626bc50a7153b347910168f9",
        "Author": "Sara",
        "StarRating": 3.5,
        "HotelName": "Ter Brughe",
        "Image": "https://lh3.googleusercontent.com/a-/AOh14Gi0QpcHD6XKePTvetRgGFTJB1w7AV_C3zrUH9p5rw=s96-c",
        "ReviewDescription": "There was an authentic vibe in the hotel, but there wasn't a shower."
    }],
    "RoomTypes":[{
        "Id": "626bc4397153b347910168f1",
        "Name": "King room",
        "NumberOfBeds": 3,
        "SquareMeters": 40,
        "Television": true,
        "Breakfast": true,
        "Airco": true,
        "Wifi": true,
        "View": true,
        "Price": 273,
        "HotelName": "Ter Brughe",
        "Image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/311191609.jpg?k=1c95c6a7a93f12e232871fa7379970fa3089e9ce8527daa50cf75337d896e465&o="
    },
    {
        "Id": "626bc48c7153b347910168f2",
        "Name": "Deluxe room",
        "NumberOfBeds": 2,
        "SquareMeters": 30,
        "Television": true,
        "Breakfast": true,
        "Airco": true,
        "Wifi": true,
        "View": false,
        "Price": 240,
        "HotelName": "Ter Brughe",
        "Image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/311191598.jpg?k=21cc7ae84af70ed7bdff087ca8b94a914df8de7365c5adbe5b6170a00795c123&o="
    },
    {
        "Id": "626bc49e7153b347910168f3",
        "Name": "Economic",
        "NumberOfBeds": 2,
        "SquareMeters": 20,
        "Television": true,
        "Breakfast": true,
        "Airco": false,
        "Wifi": true,
        "View": false,
        "Price": 215,
        "HotelName": "Ter Brughe",
        "Image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/321943472.jpg?k=6876471af7e3e8e5b0fc44c4ed94ee161c394ff25058655cb1742f2cb0bd2dd3&o="
    }]
}

###

DELETE http://0.0.0.0:3000/hotel/626d61ece84e65426b0f6cc0 HTTP/1.1

###

GET http://0.0.0.0:3000/roomtypes HTTP/1.1

###

GET http://0.0.0.0:3000/roomtype/626bc3f47153b347910168ef HTTP/1.1

###

GET http://0.0.0.0:3000/roomtypes/roomname/Pr HTTP/1.1

###

GET http://0.0.0.0:3000/roomtypes/hotelname/Ter HTTP/1.1

###

POST http://0.0.0.0:3000/roomtype HTTP/1.1
Content-Type: application/json

{
       "id": "626bc49e7153b347910168f3",
        "name": "Economic",
        "numberOfBeds": 2,
        "squareMeters": 20,
        "television": true,
        "breakfast": true,
        "airco": false,
        "wifi": true,
        "view": false,
        "price": 215,
        "hotelName": "Ter Brughe",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/321943472.jpg?k=6876471af7e3e8e5b0fc44c4ed94ee161c394ff25058655cb1742f2cb0bd2dd3&o="

}

###

PUT http://0.0.0.0:3000/roomtype HTTP/1.1
Content-Type: application/json

{
    "id": "626bc48c7153b347910168f2",
    "name": "Deluxe room",
    "numberOfBeds": 2,
    "squareMeters": 30,
    "television": true,
    "breakfast": true,
    "airco": true,
    "wifi": true,
    "view": false,
    "price": 240,
    "hotelName": "Ter Brughe",
    "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/311191598.jpg?k=21cc7ae84af70ed7bdff087ca8b94a914df8de7365c5adbe5b6170a00795c123&o="
}

###

DELETE http://0.0.0.0:3000/roomtype/62449a56ba52821f2ae5cde2 HTTP/1.1

###

GET http://0.0.0.0:3000/reservations HTTP/1.1

###

GET http://0.0.0.0:3000/reservations/Name=Smithy&FirstName=John HTTP/1.1

###

GET http://0.0.0.0:3000/reservation/626d66c6e946e90e3f453b37 HTTP/1.1

###

POST http://0.0.0.0:3000/reservation HTTP/1.1
Content-Type: application/json

{
  "hotelName":"Ter Brughe","roomTypeName":"Deluxe room","incheckDate":"28-4-2022","outcheckDate":"29-4-2022","price":240,"firstName":"John","lastName":"Smithy","mail":"test@gmail.com"
}

###

PUT http://0.0.0.0:3000/reservation HTTP/1.1
Content-Type: application/json

{
    "id": "626d66c6e946e90e3f453b37",
    "lastName": "Smithy",
    "firstName": "John",
    "mail": "test@gmail.com",
    "hotelName": "Ter Brughe",
    "incheckDate": "28-4-2022",
    "outcheckDate": "30-4-2022",
    "price": 240,
    "roomTypeName": "Deluxe room"
}

###

DELETE http://0.0.0.0:3000/reservation/626d66c6e946e90e3f453b37 HTTP/1.1

###

POST http://192.168.0.151:3000/reservation 
Content-Type: application/json

{
  "hotelName":"Ter Brughe","roomTypeName":"Deluxe room","incheckDate":"28-4-2022","outcheckDate":"29-4-2022","price":240,"firstName":"John","lastName":"Smithy","mail":"test@gmail.com"
}


###

GET http://0.0.0.0:3000/reviews HTTP/1.1

###

GET http://0.0.0.0:3000/reviews/Stewart HTTP/1.1

###

GET http://0.0.0.0:3000/reviews/hotel/Neptunus HTTP/1.1

###

GET http://0.0.0.0:3000/review/626bc4be7153b347910168f4 HTTP/1.1

###

POST http://0.0.0.0:3000/review HTTP/1.1
Content-Type: application/json

{
 "id": "626bc4de7153b347910168f6",
        "author": "Wilfried",
        "hotelName": "Neptunus",
        "starRating": 4.5,
        "image": "https://cf.bstatic.com/static/img/review/avatars/ava-w/743312ca303f4a4be7af10e6d1015d40a0ce81a4.png",
        "reviewDescription": "The rooms were delightfull and the decoration was sublime."
}

###

PUT http://0.0.0.0:3000/review HTTP/1.1
Content-Type: application/json

{
    "id": "626bc4be7153b347910168f4",
  "author": "Vandeweyer",
  "hotelName": "Neptunus",
  "starRating": 4,
  "image": "https://graph.facebook.com/v2.9/802992566485650/picture?type=square&height=64&width=64",
  "reviewDescription": "They were very kind and helpfull. The breakfast was amazing and I'll go back for sure!"
}

###

DELETE http://0.0.0.0:3000/review/62449b19ba52821f2ae5cde4 HTTP/1.1

